### ISSUE TITLE
[FR] Hyperlinks on each highlight

### ISSUE THREAD

**Issue by NightMachinary** [dainiusjocas/lucene-grep#100]
Currently, hyperlinks only work for the main location prefix/header:
```
lmgrep --hyperlink --no-split -q 'daily' **/*.org
```
![image](https://user-images.githubusercontent.com/36224762/118216980-cdba7400-b489-11eb-8dfb-29135b5e9978.png)

It would be nice if we could have them on the highlighted words themselves as well, with the correct line number and column set on them.

**Comment by NightMachinary** [comment]
I just noticed line number/column is not included in the header hyperlinks as well. They are just raw filenames. This makes jumping to stuff very frictionful.

**Comment by dainiusjocas** [comment]
I've fixed this issue, now the text editor opens the correct line https://github.com/dainiusjocas/lucene-grep/issues/73
```
(ansi/link file (str (.toURI (io/file file)) "#" line-number)
``` 
Hope this helps.

**Comment by NightMachinary** [comment]
Thanks!
