### ISSUE TITLE
Maven release

### ISSUE THREAD

**Issue by vemv** [dainiusjocas/lucene-grep#214]
Hi,

I'm happy to have found this project. Kudos!

I'd like to use it as an in-process, repl-driven tool. It's how I happen to run most of my tools, and also a particularly good fit for my use case (grepping the classpath. A repl always knows the accurate classpath it's running on, with no overhead to compute it).

For that to happen, I'd need a Maven artifact. Would you be so kind to start releasing those?

Thanks - V

**Comment by dainiusjocas** [comment]
Hi, thanks for the interest. 

What should be included into this maven artifact? Only grepping? Or also things like glob pattern matching? Or also multithreaded processing?

**Comment by dainiusjocas** [comment]
Hi, after a long delay, I've finally refactored out a library out of lmgrep: https://github.com/dainiusjocas/lucene-monitor

Check it out, and let me know what can be added.

**Comment by vemv** [comment]
Thanks!

I cannot promise to immediately take a look at it, however this (the use case described in OP) would sound like a nice thing that cider-nrepl could do.

I'll add an issue there to not forget.
