### ISSUE TITLE
Lucene monitor link 404s

### ISSUE THREAD

**Issue by SevereOverfl0w** [dainiusjocas/lucene-grep#32]
README links to https://lucene.apache.org/core/8_7_0/monitor/index.html but that's giving me a 404 not found

**Comment by dainiusjocas** [comment]
OK, a quick fix is to use that link https://lucene.apache.org/core/8_2_0/monitor/index.html

**Comment by dainiusjocas** [comment]
Fixed https://github.com/dainiusjocas/lucene-grep/blob/main/README.md Thanks @SevereOverfl0w!
