### ISSUE TITLE
Search whole file

### ISSUE THREAD

**Issue by SevereOverfl0w** [dainiusjocas/lucene-grep#33]
Maybe related to #3?

I'm using this to perform topical searches in a wiki folder of markdown files (show me articles where code review and clojure are both mentioned).

Here's a dumb example of something that doesn't work that I'd like to have work:

```
❯ echo 'foo qux\nbar' | lmgrep 'foo && bar'
```

In this case, I'm less concerned about having line numbers than I am of just knowing which files matched.

**Comment by dainiusjocas** [comment]
Currently, the text is segmented into lines and is searched line by line. With #16 `lmgrep` will expose a pattern on which to split the file or not to split at all.

**Comment by dainiusjocas** [comment]
@SevereOverfl0w this change is released.

```
echo 'foo qux\nbar' | ./lmgrep 'foo && bar' --no-split
*STDIN*:1:foo qux
bar
```

Try it out: https://github.com/dainiusjocas/lucene-grep/releases/tag/v2021.02.02

**Comment by SevereOverfl0w** [comment]
This is great, thanks!
