### ISSUE TITLE
Emit hyperlinks

### ISSUE THREAD

**Issue by SevereOverfl0w** [dainiusjocas/lucene-grep#42]
There's VTE escape codes for hyperlinks.  These allow you to mark out files & their line numbers.

`ls` supports this with the `--hyperlink=auto` flag.  Kitty has an example script that wraps ripgrep to enable hyperlink support: https://sw.kovidgoyal.net/kitty/kittens/hyperlinked_grep.html?highlight=hyperlink

This uses OSC 8, https://iterm2.com/documentation-escape-codes.html https://github.com/mintty/mintty/wiki/CtrlSeqs#hyperlinks

This would allow clicking matches to open them straight in whatever is configured.  I'm searching markdown files, so it would use vim :)

**Comment by SevereOverfl0w** [comment]
Peak evil? `fd -emd -tf -X lmgrep --template "`printf "\e]8;;file://${HOSTNAME}${PWD}/{{file}}#{{line-number}}\\e\\\\{{file}}\\e]8;;\\e\\\\: {{line}}"`" --no-split inbox`

**Comment by dainiusjocas** [comment]
TIL about hyperlinks. Nice, I'll implement it next week.

**Comment by dainiusjocas** [comment]
Copied the solution from here https://github.com/sindresorhus/ansi-escapes/blob/main/index.js
