### ISSUE TITLE
Hyperlink to line number

### ISSUE THREAD

**Issue by SevereOverfl0w** [dainiusjocas/lucene-grep#73]
Hey, just got around to trying out the hyperlink feature.  Works nicely, it's great to be able to jump straight to the file.  One little bonus would be to emit `<file>#{{line-number}}` as it allows opening the file on a particular line number directly (that of the match).

**Comment by dainiusjocas** [comment]
I've tried to add a line number but all my editors refuse to open to a specific line. https://github.com/dainiusjocas/lucene-grep/pull/76

What is your terminal+editor that supports this trick?

**Comment by SevereOverfl0w** [comment]
I'm using kitty as documented here with vim: https://sw.kovidgoyal.net/kitty/kittens/hyperlinked_grep.html
