### ISSUE TITLE
Windows releases missing on the newer compiled artifacts

### ISSUE THREAD

**Issue by 111andre111** [dainiusjocas/lucene-grep#78]
The newer releases have some exciting newer features, but unfortunately the newer last seem to be missing for the last 5 releases since the last one 2021-02-28
https://github.com/dainiusjocas/lucene-grep/releases

Could we please have these back?

@dainiusjocas

**Comment by dainiusjocas** [comment]
Hi, thanks for the feedback. Sure, I'll bring back the Windows builds.

I've just added the binary to the last release. https://github.com/dainiusjocas/lucene-grep/releases/tag/v2021.04.06

Cheers!

**Comment by 111andre111** [comment]
Thank you.
