### ISSUE TITLE
[Q] incomplete word search

### ISSUE THREAD

**Issue by NightMachinary** [dainiusjocas/lucene-grep#99]
One usecase where Lucene’s tokenizing approach tends to work less well than something like grep is when for some reason we want to query for a substring of a token, e.g. if the text is “I walked through the town” and I want to search for “oug”. 

Does lmgrep offer a performant solution for this kind of case, or would it be a situation where it’s better to stick with regular grep?

**Comment by NightMachinary** [comment]
It seems this is [possible](https://stackoverflow.com/questions/5786338/document-search-on-partial-words), but the query parser needs to be configured to allow leading wildcards:
```
❯ lmgrep '--case-sensitive?' false --hyperlink --no-split -q '+nadia +diff +*tall*' **/*.org

Failed to parse query: '{:query "+nadia +diff +*tall*", :id "0", :type "QUERY"}' with exception 'org.apache.lucene.queryparser.classic.ParseException: Cannot parse '+nadia +diff +*tall*': '*' or '?' not allowed as first character in WildcardQuery'
```

**Comment by dainiusjocas** [comment]
[ngram](https://lucene.apache.org/core/8_3_0/analyzers-common/org/apache/lucene/analysis/ngram/NGramFilterFactory.html) token filter might help if you want to match in the middle of the words.

**Comment by dainiusjocas** [comment]
I will add an option to allow leading wildcards in the next release, thanks for the suggestion! This will be an addition to the effort to support multiple query parsers.
